# pnpm-workspace.yaml
packages:
  - "shared/*"
  - "apps/*"

overrides:
  better-sqlite3: "npm:empty-npm-package"

allowedDeprecatedVersions:
  prebuild-install: "7.1.3"

peerDependencyRules:
  ignoreMissing:
    - tailwindcss
    - vite
    - postcss
    - drizzle-orm
  allowedVersions:
    vite: "^8.0.0"
    "@sveltejs/vite-plugin-svelte": "^7.1.2"
    tailwindcss: "^4.0.0"
    drizzle-orm: "*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: true
  prisma: true
  "@node-rs/argon2": true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild